name: rlreels
description: A short-form video app for food vendors
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  video_player: ^2.7.0
  flutter:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
